### ISSUE TITLE
Issue when implementing the KdV equation

### ISSUE THREAD

**Issue by gotencoder** [bifurcationkit/BifurcationKit.jl#106]
Hi there,

I am trying to perform bifurcation analysis on the KdV equation using this package - I am using the pd-1d.jl example script as a template for my implementation. I am having an issue with the function 
```
    newton(probBif, optnewton, normN = norminf)
```
where an error is thrown ERROR: LoadError: type NamedTuple has no field lx.
I am not sure on the cause of this, I am happy to provide more information/code if that helps. Also to implement something like the KdV is it somewhat straightforward, or are there potential problems to consider?

Many thanks

**Comment by rveltz** [comment]
Hi
I think you forgot to put à parameter axis corresponding to the lens of your problem. Ie there is no getLens(probBof) in your getParams(probBif)

**Comment by rveltz** [comment]
For kdv, it depends 1d or 2d?
Do you want finite difference or FEM which rest on sparse matrices?
You can also use Fourier depending on your BC. In 1d there is a code available by @gibson

**Comment by gotencoder** [comment]
Hi there,

Thanks for your reply!

I have added the lx = lx part in the par_br variable and that has seemed to alleviate the problem. 
Now the Newton iterations run but the f(x) value gets really large (~5e42) and the code exits with the error 'ERROR: LoadError: SingularException(0)'

I am looking to perform analysis on a 1d kdv (currently I am considering periodic BCs) - any help/resources would be really appreciated! (I am quite new to Julia)

Many thanks!

**Comment by rveltz** [comment]
It should not be...
Can you please show me your problem and parameters?

**Comment by rveltz** [comment]
For kdv:

https://github.com/johnfgibson/julia-pde-benchmark/blob/master/1-Kuramoto-Sivashinksy-benchmark.ipynb
https://docs.sciml.ai/SciMLBenchmarksOutput/stable/

**Comment by rveltz** [comment]
The code looks fine for BifurcationKit. I guess your implementation of kdv is not good, your initial guess is not good enough, etc.

Should we close this?

**Comment by gotencoder** [comment]
Thanks for the guidance, sure happy to close this.
Is there an email/method to contact you rather than opening up a new 'issue'?

Thanks again
