### ISSUE TITLE
getperiod vs. getPeriod

### ISSUE THREAD

**Issue by axla-io** [bifurcationkit/BifurcationKit.jl#113]
Is there supposed to be a difference between these functions?
I'm assuming that `getperiod` is the old one, but it's still at some places in the source code.

**Comment by axla-io** [comment]
Same goes for `get_Ls` vs. `getL`

**Comment by rveltz** [comment]
getPeriod is the old syntax. It is not julian type of naming function, so it is now `getperiod` (on master).
I am changing a lot of function names to agree with Julia type of naming (functions, struct,...)
This is a big breaking change
I will tag a new version for this new syntax.

I encourage you to use the master of BK

**Comment by axla-io** [comment]
Thanks!
