### ISSUE TITLE
BifurcationKit incompatible with latest ModelingToolkit version

### ISSUE THREAD

**Issue by TorkelE** [bifurcationkit/BifurcationKit.jl#121]
I think at least. This is a replicate of this issue over at MTK: https://github.com/SciML/ModelingToolkit.jl/issues/2284. I am unsure in which package it is easiest to fix this.

**Comment by TorkelE** [comment]
As mentioned by Sam in https://github.com/SciML/ModelingToolkit.jl/issues/2284, BifurcationKit has SciMLBase version < 2, with 2 being the latest version.

**Comment by TorkelE** [comment]
Had a chat with Avik who said that, given changes to some SciML packages, the best approach is to wait a week or 2 until that is fixed, and then look back at this.

**Comment by rveltz** [comment]
I would tend to think it is a no brainer to update but given the size of BK, I have to make sure the tests pass. Is there some info about the changes in SciMLBase?

**Comment by TorkelE** [comment]
Unsure about the SciMLBase changes. I thought it was easy, and tried to do so locally, but when I tried to run the tests I got incompatibility issues. My impression was that something downstream of BK affected something that indirectly was incompatible with SciMLBase 2.

**Comment by TorkelE** [comment]
Will do

**Comment by TorkelE** [comment]
This should be good now

**Comment by rveltz** [comment]
I tagged a new version that solves the issue.
