### ISSUE TITLE
record from solution title looks werid in docs

### ISSUE THREAD

**Issue by TorkelE** [bifurcationkit/BifurcationKit.jl#126]
![image](https://github.com/bifurcationkit/BifurcationKit.jl/assets/18099310/6cff37af-837c-41dc-b95b-34d8e3f0e1f0)

It is written `record_from_solution` which is interpreted as emphasis on `from`. I was going to make a fixing PR (maybe trying `record\_from\_solution`), but could not actually replicate the issue locally on my machine, so could not actually check whether it got fixed.

**Comment by rveltz** [comment]
OK I see it https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/periodicOrbit/#.-record*from*solution

**Comment by rveltz** [comment]
solved on dev branch
