### ISSUE TITLE
Incorrect calls to `EventSpecialPoint`

### ISSUE THREAD

**Issue by danielwe** [bifurcationkit/BifurcationKit.jl#129]
I believe the following calls to `EventSpecialPoint` are incorrect. Their signature does not match the method definition (line 243 in the same file, see below---as far as I can tell, there's only one method definition for this function). Specifically, the calls have 6 args instead of 5, and the types don't line up.

I found this while creating #128. I don't have enough context or understanding to know what the calls should have looked like, or how to write test cases that would have caught these errors.

https://github.com/bifurcationkit/BifurcationKit.jl/blob/bdb0147f857703a3190bd7e5c8845f59dfd99f90/src/events/EventDetection.jl#L249

https://github.com/bifurcationkit/BifurcationKit.jl/blob/bdb0147f857703a3190bd7e5c8845f59dfd99f90/src/events/EventDetection.jl#L276

https://github.com/bifurcationkit/BifurcationKit.jl/blob/bdb0147f857703a3190bd7e5c8845f59dfd99f90/src/events/EventDetection.jl#L306

https://github.com/bifurcationkit/BifurcationKit.jl/blob/bdb0147f857703a3190bd7e5c8845f59dfd99f90/src/events/EventDetection.jl#L336

https://github.com/bifurcationkit/BifurcationKit.jl/blob/bdb0147f857703a3190bd7e5c8845f59dfd99f90/src/events/EventDetection.jl#L370

Here's the only method definition:

https://github.com/bifurcationkit/BifurcationKit.jl/blob/bdb0147f857703a3190bd7e5c8845f59dfd99f90/src/events/EventDetection.jl#L243

**Comment by rveltz** [comment]
indeed! Thank you

This line is never called though:

https://app.codecov.io/gh/bifurcationkit/BifurcationKit.jl/blob/master/src%2Fevents%2FEventDetection.jl#L247

I need to improve this.

**Comment by rveltz** [comment]
closed with https://github.com/bifurcationkit/BifurcationKit.jl/commit/096772dfca58fde99f4a9ccca54ff370b2e0b47b
