### ISSUE TITLE
using `ContinuationPar` directly as input to `bifurcationdiagram` (rather than `(args...) -> opts_br`)

### ISSUE THREAD

**Issue by TorkelE** [bifurcationkit/BifurcationKit.jl#132]
Currently, when I want to provide options to `bifurcationdiagram` I do something like this:
```julia

opts_br = ContinuationPar(dsmin = 0.0001, dsmax = 0.001, ds = 0.0001, max_steps = 10000, p_min = p_span[1], p_max = p_span[2], n_inversion = 4)
bif_dia = bifurcationdiagram(bprob, PALC(), 2, (args...) -> opts_br; bothside = true)
```
Wouldn't it be neater to simply permit:
```julia
bif_dia = bifurcationdiagram(bprob, PALC(), 2, opts_br; bothside = true)
```
and internally it is converted to the second? There might be some internal reason why this is not possible though?

**Comment by rveltz** [comment]
Yes it would be good! Ill look into it, I dont think there is anythinng preventing from it

**Comment by rveltz** [comment]
This should be good on master
