### ISSUE TITLE
Custom BorderedLinearSolver interface requirements for PALC are missing

### ISSUE THREAD

**Issue by Azercoco** [bifurcationkit/BifurcationKit.jl#140]
When using a custom AbstractBorderedLinearSolver as the `bls` field in `PALC( ...)`, the required interface methods as mentioned [here](https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/interfaceLS/) are not sufficient. The custom bordered solver is also expected to implements something like [this ](https://github.com/bifurcationkit/BifurcationKit.jl/blob/ba30cb4c1a6141b975b77f588b25d5df6b77c98e/src/LinearBorderSolver.jl#L129). 

It also seems that this implementation is exactly the same for all sub types of `AbstractBorderedLinearSolver`. Maybe it would be better to just implements this method for the `AbstractBorderedLinearSolver` type directly instead of having duplicated code.

**Comment by Azercoco** [comment]
Also in PALC, the solver is expected to have a field `solver`, which can be equal to `nothing` but has to be present nevertheless or the compilation will fail.

**Comment by rveltz** [comment]
Hi

Thank you for reporting this.

> Maybe it would be better to just implements this method for the AbstractBorderedLinearSolver type directly instead of having duplicated code.

I agree, thank you for the suggestion.

**Comment by rveltz** [comment]
At some point, I need to find a better way for specifying the interfaces. As for PALC, I guess you are referring to the [update](https://github.com/bifurcationkit/BifurcationKit.jl/blob/master/src/continuation/Palc.jl#L81) method. I guess I can correct this by adding the requirement that an `update` method exists for `AbstractBorderedLinearSolver`. 

Is this blocking you or you found a way out?

**Comment by Azercoco** [comment]
Yes, that was the issue, the work around I found was just to add an solver field with a nothing value. No the cleanest but it did works.

**Comment by rveltz** [comment]
You are right for the required field `solver`.

> When using a custom AbstractBorderedLinearSolver as the bls field in PALC( ...), the required interface methods as mentioned [here](https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/interfaceLS/) are not sufficient. The custom bordered solver is also expected to implements something like [this ](https://github.com/bifurcationkit/BifurcationKit.jl/blob/ba30cb4c1a6141b975b77f588b25d5df6b77c98e/src/LinearBorderSolver.jl#L129).

This I am not sure. It is a fallback that will use the custom bordered linear solver, no need to add this.

**Comment by rveltz** [comment]
solved
