### ISSUE TITLE
record_from_solution shoud have acces to the entire set of parameters

### ISSUE THREAD

**Issue by Azercoco** [bifurcationkit/BifurcationKit.jl#143]
I am encountering an issue with  `record_from_solution` on a custom problem state with a large amount of parameters I want to continue. I would like to write a common `record_from_solution` function which is independant on the parameter I chose to continue which save the full state of the problem. It would also make it more convenient when switching to codim2 continuation.

**Comment by rveltz** [comment]
I see. Perhaps the best way would be for BK to pass the ContIterable and ContState like done with finalizer

> It would also make it more convenient when switching to codim2 continuation.

Right

**Comment by rveltz** [comment]
> It would also make it more convenient when switching to codim2 continuation.

Note that you can pass the new record function to `continuation` for codim 2

**Comment by rveltz** [comment]
solved!

 https://github.com/bifurcationkit/BifurcationKit.jl/commit/f1503bca74b00d13895db2a1749ea1ea2331f1a1
