### ISSUE TITLE
Issue with passing the `record_from_solution` to the mimally augmented codim 2 continuation

### ISSUE THREAD

**Issue by Azercoco** [bifurcationkit/BifurcationKit.jl#151]
There's seems to be an issue than when using the wrapper `BK.continuation_hopf` or ` BK.continuation_fold` for a minimally augmented problem, the `record_from_solution` is not passed correctly and the recording is not made correctly, meaning we can't access the solution data in the codim bifurcation.

**Comment by rveltz** [comment]
Can we close this unless you have a MWE showing the error?

**Comment by Azercoco** [comment]
I can't reproduce it in 0.4 so I assume the situation that caused the issue is fixed/don't happen anymore.
