### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by TorkelE** [bifurcationkit/BifurcationKit.jl#154]
Would it be possible to tag a new release?

I think a while ago it was changed so that you could pass `ContinuationPar` using
```julia
opts_br = ContinuationPar(p_min = p_span[1], p_max = p_span[2], max_steps = 1000)
bif_dia = bifurcationdiagram(bprob, PALC(), 2, opts_br; bothside = true)
```
instead of
```julia
opts_br = ContinuationPar(p_min = p_span[1], p_max = p_span[2], max_steps = 1000)
bif_dia = bifurcationdiagram(bprob, PALC(), 2, (args...) -> opts_br; bothside = true)
```
However, now when I rewrite my docs to use this, I get an error. I noted that there hadn't been a release in a while, maybe this is the reason?

**Comment by rveltz** [comment]
I am on it. KrylovKit is blocking it for now.

**Comment by rveltz** [comment]
done!

**Comment by rveltz** [comment]
Is this resolved?
