### ISSUE TITLE
Facilitate solution saving at precise parameter values

### ISSUE THREAD

**Issue by BambOoxX** [bifurcationkit/BifurcationKit.jl#172]
In SciML ODE solvers, there is a built-in `saveat` option that allows to save the solution at precise time steps with interpolation between actually computed points. 

I know that BifurcationKit allors to use e.g. `SaveAtEvent`, but as advertised that is not very precise, and there is [this section](https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/faq/#How-can-I-save-a-solution-every-n-steps,-or-at-specific-parameter-values?) of the documentation, but I could not make any sense of it to save the solution at precise continuation parameter values. 

Could there be some more information, or some easier interface to facilitate such precise savings of the solution ?

**Comment by BambOoxX** [comment]
I'm guessing this step should be added in https://github.com/bifurcationkit/BifurcationKit.jl/blob/40113d058e60b60f95bf189a8e8d2e19556d4267/src/events/EventDetection.jl#L28 right ?

**Comment by rveltz** [comment]
No, this is to locate. Once it has been located, we should do something with the event. This part is not done. I guess, we should let the user pass a finaliser function to be applied to the event. In your case, the event function would be a newton algorithm.

**Comment by BambOoxX** [comment]
So you mean add a Newton iteration in 
https://github.com/bifurcationkit/BifurcationKit.jl/blob/40113d058e60b60f95bf189a8e8d2e19556d4267/src/events/BifurcationDetection.jl#L8
or did you have something else in mind ?

**Comment by rveltz** [comment]
probably the easiest would be to dispatch on `SaveAtEvent` the function `get_event_type`

https://github.com/bifurcationkit/BifurcationKit.jl/blob/40113d058e60b60f95bf189a8e8d2e19556d4267/src/Continuation.jl#L522

Something like 

```
function get_event_type(event::SaveAtEvent, 
                        iter::AbstractContinuationIterable, 
                        state, 
                        verbosity, 
                        status::Symbol, 
                        interval::Tuple{T, T}, 
                        ind = :; 
                        typeE = "userC") where T

# do newton here
end
```
This is a hack that would probably work. The best way would be to add a finalizer function in all events `ContinuousEvent`, etc and call this finalizer (inplace) just after https://github.com/bifurcationkit/BifurcationKit.jl/blob/40113d058e60b60f95bf189a8e8d2e19556d4267/src/Continuation.jl#L522

**Comment by BambOoxX** [comment]
> This is a hack that would probably work. However, it is not a general solution because if you use a Pair of events with `SaveAtEvent`, it would not call the dispatched function.

What about a dispatch over any `PairOfEvent` that contains a `SaveAtEvent` ? 

I just looked at [`locate_bifurcation!`](https://github.com/bifurcationkit/BifurcationKit.jl/blob/40113d058e60b60f95bf189a8e8d2e19556d4267/src/Bifurcations.jl#L144). I was thinking about using that as a base for the Newton steps, do you see any disavantages of using that ?

**Comment by rveltz** [comment]
It depends what you want to do:
1. if you want a solution for yourself, I provided the best hack above IMO
2. if you want a solution for the library, we have to be really careful as some code is very sensitive (like `locate_bifurcation`), plus we have to provide a nice API for the user.

**Comment by BambOoxX** [comment]
I would say, I'd love a solution for myself, but also for the library ;). 
I was also wondering if, since we have the solution with a nice resolution in the end, we could perform an interpolation on a branch with e.g. `ApproxFun` and evaluate at the requested points...

**Comment by rveltz** [comment]
Solved.

**Comment by BambOoxX** [comment]
@rveltz Hi, I'm getting back at this, after dropping the ball for a very long time, is this section of the doc the answer to this issue ?

https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/faq/#How-can-I-save-a-solution-every-n-steps,-or-at-specific-parameter-values?

**Comment by rveltz** [comment]
No it does not. This [one](https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/EventCallback/#BifurcationKit.SaveAtEvent) does.

**Comment by BambOoxX** [comment]
@rveltz ah yes, I see., thanks. 

While playing a bit with parameters, it seems that when the `ds` is quite large, multiple `SaveAtEvent` can be located in a single solution interval, leading to them being sort of merged. 
If this is expected, it could be useful to be able to set large `ds` and let the bisection do its work for all detected events in an interval. 

The special point looks like this on a specific case : 
>  - \# 23, save-117save-118save-119save-120save-121

**Comment by rveltz** [comment]
yes this is expected given the current bissection algorithm.
It could be improve though
