### ISSUE TITLE
DefCont doesn't support `bothside` kwarg

### ISSUE THREAD

**Issue by axla-io** [bifurcationkit/BifurcationKit.jl#186]
Calling `continuation` with `bothside=true` errors if one uses DefCont, but not for PALC()

**Comment by rveltz** [comment]
Why did you close it?

**Comment by axla-io** [comment]
Correct me if I'm wrong, but I got the feeling that this is intended behavior?

**Comment by rveltz** [comment]
No it is just something I did not think about. It is perfectly OK to ask this, and it is not very difficult to add.
