### ISSUE TITLE
Skip bifurcation point type check for multicontinuation?

### ISSUE THREAD

**Issue by axla-io** [bifurcationkit/BifurcationKit.jl#187]
Let's say I want to do a multicontinuation on new branches from a point at index `id`
``` 
bp = get_normal_form(br, id)
δp = 0.005
pred = predictor(bp, δp)
pts = BifurcationKit.get_first_points_on_branch(br, bp, pred, opts_br; δp)
```

I'm frequently encountering that my point gets misclassified as `hopf` when it's supposed to be `nd` and then `get_first_points_on_branch` throws a type error. Would it make sense to skip this type check? For me it'd be beneficial since I know the type of bifurcation and don't want to spend time changing parameters to get it properly detected.

**Comment by rveltz** [comment]
In this case, do you have vanishing imaginary part of the eigenvalues? Like the bifurcating eigenvalues are

```
1e-9 + 1e-9im
```

The code for bifurcation type inference is https://github.com/bifurcationkit/BifurcationKit.jl/blob/master/src/Bifurcations.jl#L70

**Comment by rveltz** [comment]
is it solved?

**Comment by axla-io** [comment]
Yes, I figured it out!
