### ISSUE TITLE
Precompilation failure

### ISSUE THREAD

**Issue by twildi** [bifurcationkit/BifurcationKit.jl#188]
Error:

> Failed to precompile BifurcationKit [0f109fa4-8a5d-4b75-95aa-f515264e7665] to "/home/xxx/.julia/compiled/v1.11/BifurcationKit/jl_VkqJmD".
> ERROR: LoadError: ArgumentError: invalid type for argument A in method definition for rmul! at /home/xxx/.julia/packages/BifurcationKit/KwA2l/src/BorderedArrays.jl:69
> Stacktrace:
>  [1] top-level scope
>    @ ~/.julia/packages/BifurcationKit/KwA2l/src/BorderedArrays.jl:69
>  [2] include(mod::Module, _path::String)
>    @ Base ./Base.jl:557
>  [3] include(x::String)
>    @ BifurcationKit ~/.julia/packages/BifurcationKit/KwA2l/src/BifurcationKit.jl:1
>  [4] top-level scope
>    @ ~/.julia/packages/BifurcationKit/KwA2l/src/BifurcationKit.jl:24
>  [5] include
>    @ ./Base.jl:557 [inlined]
>  [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
>    @ Base ./loading.jl:2806
>  [7] top-level scope
>    @ stdin:4
> in expression starting at /home/xxx/.julia/packages/BifurcationKit/KwA2l/src/BorderedArrays.jl:69
> in expression starting at /home/xxx/.julia/packages/BifurcationKit/KwA2l/src/BifurcationKit.jl:1
> in expression starting at stdin:

Steps to reproduce : 

1. Start with a Fresh Julia install 
2. `] add BifurcationKit`

I got this error with Julia 1.11 and confirmed it across three different systems.

**Comment by twildi** [comment]
It seems to be linked to KrylovKit@0.8.2 (https://github.com/Jutho/KrylovKit.jl/releases/tag/v0.8.2)
Reverting to v0.8.1 fixes the issue.

**Comment by TorkelE** [comment]
I am also suffering from this.

**Comment by rveltz** [comment]
It's because RecursiveVec is deprecated in KrylovKit. Ill tag a new vesion asap once I am sure nothing is broken

**Comment by rveltz** [comment]
https://github.com/Jutho/KrylovKit.jl/issues/102

**Comment by Datseris** [comment]
I'm getting the same issue and now Attractors.jl docs do not build anymore :D

**Comment by rveltz** [comment]
This is almost resolved on BK side now that KrylovKit has corrected the issue

**Comment by rveltz** [comment]
should be solved on master

**Comment by twildi** [comment]
It works on my side. Thanks!

**Comment by Datseris** [comment]
If this is fixed on `main` branch why isn't there a release out?

**Comment by rveltz** [comment]
No it was tagged yesterday: 0.4.4

Sorry, I did not notify you
