### ISSUE TITLE
abort continuation step when the first bifurcation point is located using the bisection

### ISSUE THREAD

**Issue by LEquinoxy** [bifurcationkit/BifurcationKit.jl#192]
Hello again! I want to use continuation to find the stable range of system parameters. To reduce computation time, I would like to stop the continuation of a branch once a bifurcation point (e.g., ns point or hopf point) is located using the bisection. How should I write the function to pass to `callback_newton`?

**Comment by rveltz** [comment]
Hi,

Use a finalizer and check `contResult.specialpoint`

**Comment by LEquinoxy** [comment]
Issue has been solved.Thank you do much!😄😄
