### ISSUE TITLE
Formulate some examples using ModelingToolkit

### ISSUE THREAD

**Issue by finmod** [bifurcationkit/BifurcationKit.jl#51]
For better visibility and integration of BifurcationKit with SciML, some examples, in particular DAE and PDE, should be formulated using MTK with its automatic Jc features.

Also, BifurcationKit should have better visibility in the SciML ecosystem.

**Comment by rveltz** [comment]
Do you have an example in mind? ODE, DAE, PDE?

**Comment by finmod** [comment]
I suggest to ask @ChrisRackauckas. Two hints: https://si.sciml.ai/dev/tutorials/using_modeling_toolkit/ and the README example of https://github.com/SciML/ModelingToolkit.jl .

**Comment by rveltz** [comment]
It has now examples on MTK docs
