### ISSUE TITLE
Allow using other Makie backends

### ISSUE THREAD

**Issue by sceptri** [bifurcationkit/BifurcationKit.jl#54]
Right now, only GLMakie backend is allowed, for e.g. WGLMakie or CairoMakie, RecipesMakie.jl is not loaded (as per [this line](https://github.com/rveltz/BifurcationKit.jl/blob/4bc09399d790f7b23c0fcfeb38808db968fb5ea3/src/BifurcationKit.jl#L84))

Also, RecipesMakie.jl seems to only support GLMakie (but that's only my assumption).

Thanks a lot

**Comment by rveltz** [comment]
I dont really know Makie that well. The best way would be to create a package `BifurcationKitMakie.jl` in the orgranisation [bifurcationkit](https://github.com/bifurcationkit) and put the Makie code there.

Have you tried the backends WGLMakie or CairoMakie with my code (by altering the [line](https://github.com/rveltz/BifurcationKit.jl/blob/4bc09399d790f7b23c0fcfeb38808db968fb5ea3/src/BifurcationKit.jl#L84)) ? Does it work?

**Comment by rveltz** [comment]
This part has been refactored. If you want to update it for CairoMakie, it's be awesome!
