### ISSUE TITLE
Support for delay differential equations

### ISSUE THREAD

**Issue by whilo** [bifurcationkit/BifurcationKit.jl#66]
Hey,

Thanks for the very nice package! I have explored the examples a bit, but my dynamics is actually described as a delay differential equation (DDE) and I would like to know whether support is planned for DDEs? It seems that DDE-BIFTOOL [1] is a common Matlab/Octave based analysis solution, but I would prefer a Julia based one.

Best,
Christian

[1] http://ddebiftool.sourceforge.net/demos/neuron/html/demo1_simple.html

**Comment by rveltz** [comment]
Hi,

Support is planned but the timeframe is uncertain. It depends on what you want to do actually
1. constant / state dependent delays
2. stability of fixed points
3. codim 2 of fixed points
4. computing periodic orbits


If you want to compute the stability of equilibrium for constant delays, the only thing to do is provide the right jacobian and eigenvalue solver. This is probably 1h of work. For state dependent delays, it requires a bit more work. Note that you can use https://nep-pack.github.io/NonlinearEigenproblems.jl/dev/ for the eigensolver, so it is very little work.

If you want to compute codim 2 of equilibria, it requires more work, especially around the normal forms.

If you want to compute periodic orbits, the method has to be written from scratch, not a lot work but still.

**Comment by rveltz** [comment]
new package [DDEBifurcationKit.jl](https://github.com/bifurcationkit/DDEBifurcationKit.jl)

**Comment by whilo** [comment]
Thank you! Our problem seems to be not directly bifurcation related, but I will check it out when I need it!
