### ISSUE TITLE
Generalized eigenvalue problem during continuation

### ISSUE THREAD

**Issue by yhchang96** [bifurcationkit/BifurcationKit.jl#75]
So my problem involves finding steady states of a 4th order nonlinear [PDE](https://en.wikipedia.org/wiki/Thin-film_equation) and determining the stability, and I have a couple questions:

1. If I don't pass any Jacobian to `continuation(prob, PALC(), optcont)`, is the default used by the solver simply using `ForwardDiff.jacobian`? At least when I pass `J=(u,par)->ForwardDiff.jacobian(fun(z,par),u)` the result seems to be exactly the same as that when I don't set anything for `J`, but I want to confirm if this is indeed the case.

2. When I set `continuation( ... ; detectBifurcation=1, nev=4)`, how are the eigenvalues/eigenvectors computed? Is the default using `LinearAlgebra.eigen`? I find that the eigenvalues/eigenvectors returned from `continuation` is not exactly the same as the comes I get from `eigen(Amat)` where `Amat` is the Jacobian computed using `ForwardDiff.jacobian`. Since the problem size is not that big (~256 grid points) and I'm still at the stage of making things work/give correct results I'm not using sparse matrix/iterative methods for now.

3. Now for my problem I find that instead of (A) having a function to compute `F(u)=0` which involves fourth-order derivatives, it seems that I get 'better' solutions if I (B) split `u=(u1,u2)` where `u2` is the second derivative of `u1`, so that `F(u1,u2)` involves only second derivatives at most. I say B is 'better' because method A sometimes gives results which contradict with previous studies/physical intuition (e.g. I expect -ve eigenvalues but it gives +ve, or the eigenvectors is slightly skewed where it should be symmetric) while method B so far doesn't give any strange results. Now the problem for method B is that when written as `M*du/dt = F(u)`, the mass matrix is singular (the first half of `F(u)` is the original discretized PDE, while the new augmented second half simply related `u1` and `u2` but not any `d/dt` so `M` has zeros along diagonal). I don't have problems using `continuation` to solve for steady states in method B, but I don't know how to do eigenvalue analysis (`detectBifurcation=1`) as well with a singular mass matrix.

**Comment by rveltz** [comment]
1. yes see [here](https://github.com/bifurcationkit/BifurcationKit.jl/blob/master/src/Problems.jl#L176)
2. I dont understand you need to pass a `opts :: ContinuationPar` to `continuation`. For eigenvalues computation you need `opts.detectBifurcation >0`. The eigensolver used is `opts.newtonOptions.eigsolver`
3. you have to define your own eigensolver. For DAE this is done in this [tutorial](https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/tutorials/ode/Colpitts/#Colpitts%E2%80%93type-Oscillator-(Intermediate)). The same is done for the wave, see [waves eigensolvers](https://github.com/bifurcationkit/BifurcationKit.jl/blob/master/src/wave/EigSolver.jl)
