### ISSUE TITLE
Event function not called while doing codim2 fold point continuation

### ISSUE THREAD

**Issue by yhchang96** [bifurcationkit/BifurcationKit.jl#76]
Using the temperature model in the tutorial as an example:

```
using BifurcationKit, LinearAlgebra, Parameters, Setfield
const BK = BifurcationKit

Nop(x; a = 0.5, b = 0.01) = 1 + (x + a*x^2)/(1 + b*x^2)

function F_chan(x, p)
    α, β = p.α, p.β
    f = similar(x)
    n = length(x)
    f[1] = x[1] - β
    f[n] = x[n] - β
    for i=2:n-1
        f[i] = (x[i-1] - 2 * x[i] + x[i+1]) * (n-1)^2 + α * Nop(x[i], b = β)
    end
    return f
end

function test_event1(iter, state)
    α_ref = 3.8
    #println("testing: event function working!")   # to test whether this event function is being called
    return state.z.p - α_ref
end

n = 101
sol0 = [(i-1)*(n-i)/n^2+0.1 for i=1:n]
par = (α = 3.3, β = 0.01)
prob = BifurcationProblem(F_chan, sol0, par, (@lens _.α))
optcont = ContinuationPar(dsmin = 0.01, dsmax = 0.05, ds= 0.01, pMin = 0., pMax = 4.2,
    newtonOptions = NewtonPar(maxIter = 10, tol = 1e-9), saveSolEveryStep=1,
    detectEvent=2, detectBifurcation=0)
br = continuation(prob, PALC(), optcont, event=BK.ContinuousEvent(1, test_event1, ("test1",)))

outfoldco = continuation(br, 2, (@lens _.β), optcont, event=BK.ContinuousEvent(1, test_event1, ("test1",)))
```

I want to use the event function `test_event1` to obtain the parameters and solutions whenever α=3.8. This works for the first continuation. But when I want to do continuation at the fold point, it looks like the event function is not even being called (if I uncomment the `println` statement I see it being printed in terminal for `br` but not for `outfoldco`). I would like to know if this is intended or what else I did wrong.

And I have another question about codim2 fold point continuation (lmk if I should ask elsewhere or open another issue): suppose I let `a` in `Nop` to be the third parameter in `par`. After getting `br` (vary `α`) and `outfoldco` (vary `α` and `β` along fold point), is it possible to do fold point continuation along an arbitrary point of the path from `outfoldco` with the third parameter, i.e. vary `α` and `a` along fold?

**Comment by rveltz** [comment]
> I want to use the event function test_event1 to obtain the parameters and solutions whenever α=3.8. This works for the first continuation. But when I want to do continuation at the fold point, it looks like the event function is not even being called (if I uncomment the println statement I see it being printed in terminal for br but not for outfoldco). I would like to know if this is intended or what else I did wrong.

it is a bug. I will correct this. Thank you

> And I have another question about codim2 fold point continuation (lmk if I should ask elsewhere or open another issue): suppose I let a in Nop to be the third parameter in par. After getting br (vary α) and outfoldco (vary α and β along fold point), is it possible to do fold point continuation along an arbitrary point of the path from outfoldco with the third parameter, i.e. vary α and a along fold?

please open another issue. The answer is yes

**Comment by rveltz** [comment]
should be fixed on master.
