### ISSUE TITLE
Is it possible to provide derivatives with respect to the parameter "p" ? + Minimal example with fold bifurcations that doesn't work

### ISSUE THREAD

**Issue by Nidish96** [bifurcationkit/BifurcationKit.jl#83]
Thanks for this package, it's really nice!

In BifurcationProblem (https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/library/#BifurcationKit.BifurcationProblem) , I found that it's possible to provide the Jacobian wrt "x" (the list of unknowns). However, it seems to be doing finite difference for the derivatives wrt to the paramter p by default. Is it possible to provide a function handle for this too?

Here's a minimal example for the Duffing Oscillator that doesn't work and I'm not sure why. 
```
using BifurcationKit: detectFold
using BifurcationKit, Plots, Setfield

Fun(x, par) = [-(par.F*sin(x[2])+par.c*par.ω0*x[1])/2par.ω0; (par.ω0-par.Ω)-(4par.F*cos(x[2])-3par.α*x[1]^3)/(8par.ω0*x[1])];
Jac(x, par) = [-par.c/2 -par.F/2par.ω0; (4par.F*cos(x[2])-3par.α*x[1]^3)/(8par.ω0*x[1]^2)+9par.α*x[1]/8par.ω0 par.F*sin(x[2])/(2par.ω0*x[1])];
dFun(x, par, dx) = Jac(x, par)*dx;

params = (ω0 = 2, c = 0.01, α = 0.1, F = 0.1, Ω = 0.1)

prob = BifurcationProblem(Fun, [0.01;0.0], params, (@lens _.Ω), J=Jac, dF=dFun);
opts = ContinuationPar(pMin = 0.1, pMax = 3.5, detectFold=true);

br = continuation(prob, PALC(), opts; plot=true);
```

**Comment by rveltz** [comment]
> However, it seems to be doing finite difference for the derivatives wrt to the paramter p by default. Is it possible to provide a function handle for this too

Not yet. I plan to do this but there are some issues with codim 2 bifurcations.

This seems to work: (I am not sure about your jacobian)

```julia
prob = BifurcationProblem(Fun, [0.01;0.0], params, (@lens _.Ω));
opts = ContinuationPar(pMin = 0.1, pMax = 3.5, maxSteps = 200);

br = continuation(prob, PALC(), opts; plot=true);
```

**Comment by Nidish96** [comment]
Ah I see! It'd be a shame not to use analytical p-gradients - I look forward to seeing more on this.

For the considered example, I seem to be running into spurious results (I got rid of my jacobians and used your modified lines of code):
![image](https://user-images.githubusercontent.com/17080531/221181849-db4420d6-6d67-4f17-a0fc-06d90852de95.png)

Here's the results for the same example with MatCont (which seems to give the right results):
![image](https://user-images.githubusercontent.com/17080531/221182210-1efd7fc3-e524-432e-9fbd-294b81cbb0cd.png)

**Comment by Nidish96** [comment]
Thanks!

Regarding this example, it's of course just a toy example I'm playing with, while I intend to apply this for much larger problems where the computation of p-gradients might be more expensive. But I wasn't quite able to follow what your code snippet above seeks to achieve. 

Also, I'm quite confident that there are no other solution branches in the region. Here's a contour plot from maxima, where it's quite clear that the contour corresponding to 0 (which is the solution) does not have any other branches that look like what BifurcationKit's giving:
![image](https://user-images.githubusercontent.com/17080531/221196285-d64a5e31-17f9-4d5f-a069-848079a2e154.png)

**Comment by rveltz** [comment]
> But I wasn't quite able to follow what your code snippet above seeks to achieve.

I meant try instead:

```julia
br = continuation(prob, PALC(tangent = Bordered()), opts; plot=true);
br = continuation(prob, MoorePenrose(), opts; plot=true);
```

> Here's a contour plot from maxima, where it's quite clear that the contour corresponding to 0 (which is the solution) does not have any other branches that look like what BifurcationKit's giving:

What if you allow to look for larger A0?
What is maxima?

**Comment by Nidish96** [comment]
I see, thanks!

Maxima is the Computer Algebra System (CAS) I use for quick checks (https://maxima.sourceforge.io/). This is what I get if I increase the range of A0:
![image](https://user-images.githubusercontent.com/17080531/221231501-69a982e3-1c63-4f6f-b1fa-93e021672133.png)

**Comment by rveltz** [comment]
```julia
prob = BifurcationProblem(Fun, [0.01;0.0], params, (@lens _.Ω); recordFromSolution = (x,p) -> x[1]);
alg = PALC(tangent = Bordered())
br = continuation(prob, alg, opts)
```

gives


<img width="603" alt="Screenshot 2023-02-24 at 20 38 13" src="https://user-images.githubusercontent.com/1591812/221275066-bede6db3-a36a-475e-895b-c18353aa75f2.png">

**Comment by Nidish96** [comment]
Okay it works perfectly now, thanks! I think it was previously just not plotting the right quantity. Thank you!

I will close this issue now, but I hope it becomes possible to supply at least a few of the p-derivatives in the future versions. Thanks for a great library!
