### ISSUE TITLE
Reexport Setfield

### ISSUE THREAD

**Issue by Datseris** [bifurcationkit/BifurcationKit.jl#85]
It appears that Setfield.jl is an integral part of BifurcationKit.jl and BifurcationKit.jl cannot be used without Setfield.jl, due to the call signature:
```
BifurcationProblem{Tvf, Tu, Tp, Tl<:Setfield.Lens, Tplot, Trec} <: BifurcationKit.AbstractAllJetBifProblem
```

Please improve user experience by using the Reexport.jl package and re-exporting Setfield.jl.

**Comment by rveltz** [comment]
Thank you for the advice. Will do

**Comment by rveltz** [comment]
Solved on master.
