### ISSUE TITLE
Document what short names of bifurcations stand for

### ISSUE THREAD

**Issue by Datseris** [bifurcationkit/BifurcationKit.jl#87]
It would be nice if the docstring of `SpecialPoint` ([SpecialPoint](https://bifurcationkit.github.io/BifurcationKitDocs.jl/stable/library/#BifurcationKit.SpecialPoint)) documents what short name is given to the bifurcations. Like, what does `bp` mean, etc. There are many different names : `ns, nd, pd, bd` to name a few. 

I think assuming prior knowledge of what it means isn't the best solution, not only because it isn't particularly suited for beginners, but also because different people call some points differently, e.g., I would cal `bp` `sd` instead (for saddle-node).

**Comment by rveltz** [comment]
I agree, will do. Also, I call them specialpoint and not bifurcationpoint because this structure is also used for storing event point that the user might declare, see https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/EventCallback/

**Comment by Datseris** [comment]
Yes, I've noticed that. Perhaps on this front it is worth adding one more field `isbifurcation::Bool`, so that it is easy to filter them. At the moment I do `sp.type == :endpoint && continue` but this doens't catch all cases. In general, I prefer to be able to access the plotted information directly instead of trying to extract it. Since you agree that this is the most important information, since this is what is plotted by default, it should be easily accessible.

**Comment by rveltz** [comment]
> Perhaps on this front it is worth adding one more field isbifurcation::Bool, so that it is easy to filter them. At the moment I do sp.type == :endpoint && continue but this doens't catch all cases.

It depends, why do you want to skip events that you asked for detection and named yourself? You can also detect bifurcations in a user defined event, in which case, I have to devise an interface to access the new field you suggest from the Event interface.

However, I see the point for `:endpoint`

**Comment by Datseris** [comment]
I didn't name any events in my code though. This is what is stored out of the box!

Regardless, events that I name myself and events that are bifurcations seem to be different at a fundamental level anyways, so I think they should be stored at different containers. One of the main reasons to use a bifurcation software is well, to find the bifurcations, so I would expect this information to be stored in its own dedicated container because this is a rather special information.

**Comment by rveltz** [comment]
It is partly solved, see https://github.com/bifurcationkit/BifurcationKit.jl/blob/master/src/BifurcationPoints.jl#L15
Remains to add the field `isbifurcation::Bool`

**Comment by rveltz** [comment]
I am wondering if providing à function would not be enough? A function based on the spécial point name. It would not require changing structs and friends

**Comment by Datseris** [comment]
Providing a function would indeed be enough. I imagine you mean a functio ntaht takes in the `br` output and returns you a vector of the detetxed bifurcation points, right?

**Comment by Datseris** [comment]
(in fact, in Julian design, this approach is much better: it is typically recommended that the API is based on functions that given a type they return the quantity of interest, rather than accessing the fields of the type directly)

**Comment by rveltz** [comment]
I could do both:

1. add a field `isbifurcation` to `SpecialPoint` and a function (getter) `isbifurcation(pt::SpecialPoint) = pt.isbifurcation`, or
2. `isbifurcation(pt::SpecialPoint) = pt.type in (:bp, :fold, :hopf)` and leave `SpecialPoint` as is.

The second solution is by far the easiest but less fast.

**Comment by Datseris** [comment]
> The second solution is by far the easiest but less fast.

This performance difference is miniscule and shouldn't affect your design. However, I was referring to a getter function `bifurcation_points(br::Branch) -> Vector{SpecialPoint}`.

**Comment by rveltz** [comment]
solved with https://github.com/bifurcationkit/BifurcationKit.jl/commit/ea29ebecebcf8a36ca4b35042e0d9d87f52a8c0d
