### ISSUE TITLE
Use Julian style of code?

### ISSUE THREAD

**Issue by Datseris** [bifurcationkit/BifurcationKit.jl#89]
I've noticed that most names/options in BifurcationKit.jl does not follow the Julia style guide when it comes to naming: https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/ 

If anything, it seems to be a style of a different language altogether, as there is no point where `snakeCase` should be used (according to the official guide). This raises a conceptual disconnect when using this package. Using the style guide comes with a lot of benefits, see e.g. slide number 11 here: https://github.com/JuliaDynamics/GoodScientificCodeWorkshop/blob/main/block2_clearcode/block2_slides.pdf  

![image](https://user-images.githubusercontent.com/19669089/230359254-528dfe23-8877-4451-997d-587b555ea3e3.png)

 Is there a solid reason that all keyword arguments are `snakeCase` instead of `low_case_with_underscores` ? If not, perhaps it is worth considering changing these things in a 1.0 release.

**Comment by rveltz** [comment]
I would say that the only convention I am not using is the function names `sakeCase` versus `snake_case`. Module and struct start with a upper case.

I will change this, you are right

**Comment by rveltz** [comment]
I will comply! I just have a bigger project to commit before making these changes.

**Comment by rveltz** [comment]
Hi,

The last version should address most of this

**Comment by hinsley** [comment]
Hello, please note that the documentation does not reflect this change (neither docstrings nor the tutorial sample code online). This is confusing for new users, though not difficult to fix.

**Comment by rveltz** [comment]
The dev is up to date:
https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/


I will tag a new version of the doc soon

**Comment by rveltz** [comment]
Is it more up to the standards now? We have been working a lot on this.

**Comment by rveltz** [comment]
Feel free to re-open if you spot some non Julian choice
