### ISSUE TITLE
No way to set BifFunction's delta parameter

### ISSUE THREAD

**Issue by antoine-levitt** [bifurcationkit/BifurcationKit.jl#99]
If I understand correctly it's hardcoded to 1e-8? Could it be a kwarg to BifurcationProblem?

**Comment by rveltz** [comment]
Indeed, this is a bug. Note that it is used for normal form and codim2 continuation, not for PALC as the doc string wrongly suggests. See https://github.com/bifurcationkit/BifurcationKit.jl/blob/master/src/continuation/Palc.jl#L407

If you want to change delta in PALC, change your `ContinuationPar`

**Comment by rveltz** [comment]
this is solved on master
